--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/UIPlugins/PvPUI
branches:
- master
projects:
  PvPUI:
    path: ""
    libs:
      - src: UIPlugins/libBoolUI/libBoolUI
        version: ^1.0.0
        vendor: poggit-project
...